site_name: EEArchive
repo_url: https://github.com/ZJUISEELab/EE-Archive/tree/main
repo_name: ZJUISEELab/EE-Archive
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 cyc-987

nav:
  - 主页: 
    - index.md
    - 贡献模版: template.md

# from mkdocs-material installation documentation
theme:
  name: material
  language: zh

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: white
      accent: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer

    - header.autohide

    - search.suggest
    - search.highlight

    - content.action.edit

extra:
  social:
    - icon: simple/github
      link: https://github.com/cyc-987
      name: Author's GitHub

plugins:
  - search
  - tags

  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  - git-committers:
      repository: ZJUISEELab/EE-Archive
      branch: main
      enabled: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true